### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by mrjcleaver** [gaborauth/toolboox#6]
Thanks

**Comment by mrjcleaver** [comment]
Quite simple!

1. On the Boox, use Neobrowser to visit https://toolboox.online/changelog
2. Click the most recent
3. Override the security warning by adding this site
4. Install

https://www.androidauthority.com/how-to-install-apks-31494/  advises against installing directly from a website, unless the APK is listed on https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=toolboox (which this is not).

**Comment by gaborauth** [comment]
It is not listed in APK mirror sites because of it is working only on the Boox devices because of the Onyx Boox SDK integration.

**Comment by gaborauth** [comment]
https://github.com/gaborauth/toolboox/wiki/How-to-install-it
